language: cpp
compiler: gcc

install:
 - cd serd
 - ./waf configure
 - ./waf
 - sudo ./waf install
 - cd ../
 - sudo apt-get install build-essential cmake m4 automake peg libtool autoconf

script: make rdf_test
