language: cpp
compiler: gcc

install:
 - cd serd
 - ./waf configure
 - ./waf
 - sudo ./waf install
 - cd ../libneo4j-client
 - ./autogen.sh
 - cd ../
 - sudo apt-get install neo4j

script:
 - make
 - sudo neo4j start -env NEO4J_AUTH=neo4j/pass
 - ./main
